version: "2"

checks:
  similar-code:
    config:
      threshold: 110 # Golang default: 100
  identical-code:
    config:
      threshold: 110 # Golang default: 100

plugins:
  golint:
    enabled: false
  govet:
    enabled: false
  gofmt:
    enabled: false

exclude_patterns:
  - "**/*_mock.go"
  - "**/*_test.go"
