run:
  go: "1.22"

linters-settings:
  cyclop:
    max-complexity: 15
  errcheck:
    check-type-assertions: true
    check-blank: true
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 15
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - hugeParam        # No golang generic support. See https://github.com/golangci/golangci-lint/issues/2649
      - rangeValCopy     # ^
      - typeDefFirst     # |
      - paramTypeCombine # |
  interfacebloat:
    max: 12
  lll:
    line-length: 150
  makezero:
    always: true
  misspell:
    locale: US
  mnd:
    # don't include "assign"
    checks:
    - argument
    - case
    - condition
    - operation
    - return
  nakedret:
    max-func-lines: 5
  varnamelen:
    ignore-decls:
      - err error
      - ok bool
      - r *http.Request
      - w http.ResponseWriter
      - r runner.Runner
      - r Runner
      - wg sync.WaitGroup

linters:
  enable-all: true
  disable:
    - contextcheck
    - depguard
    - exhaustive
    - exhaustruct
    - gochecknoglobals
    - gomoddirectives
    - gomodguard
    - ireturn
    - nlreturn

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - noctx
        # Always closing the HTTP body unnecessarily complicates the tests
        - bodyclose
        # We don't need to wrap errors in tests
        - wrapcheck