run:
  go: "1.23"

linters:
  enable-all: true
  disable:
    - contextcheck
    - depguard
    - exhaustive
    - exhaustruct
    - gochecknoglobals
    - gomoddirectives
    - gomodguard
    - ireturn
    - nlreturn
    - nonamedreturns
    - paralleltest
    - testpackage
    - varnamelen
    - wsl
    # Deprecated
    - execinquery
    - exportloopref
    - gomnd

linters-settings:
  cyclop:
    max-complexity: 15
  errcheck:
    check-type-assertions: true
    check-blank: true
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 15
  interfacebloat:
    max: 12
  lll:
    line-length: 150
  makezero:
    always: true
  misspell:
    locale: US
  nakedret:
    max-func-lines: 5

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        # Always closing the HTTP body unnecessarily complicates the tests
        - bodyclose
        - funlen
        - noctx
        # We don't need to wrap errors in tests
        - wrapcheck
