# Configuration of the Poseidon webserver
server:
  # Address on which the webserver listens
  address: 127.0.0.1
  # Port on which the webserver listens
  port: 7200
  # If set, this token is required in the Poseidon-Token header for each route except /health
  token: SECRET
  # Configuration of TLS between the web client and Poseidon.
  tls:
    # If set, the API uses TLS for all incoming connections.
    active: true
    # The path to the certificate file used for TLS
    certfile: ./poseidon.crt
    # The path to the key file used for TLS
    keyfile: ./poseidon.key
  # If true, an additional WebSocket connection will be opened to split stdout and stderr when executing interactively
  interactiveStderr: true
  # If set, the file at the given path overwrites the default Nomad job file in internal/environment/template-environment-job.hcl
  templateJobFile: ./poseidon.hcl

# Configuration of the used Nomad cluster
nomad:
  # IP address / domain of the Nomad server
  address: 127.0.0.1
  # Port of the Nomad server
  port: 4646
  # Authenticate requests to the Nomad server with this token
  token: SECRET
  # Configuration of TLS between the Poseidon and Nomad.
  tls:
    # Specifies whether to use TLS when communicating with the Nomad server.
    active: false
    # The path to the certificate of the CA authority of the Nomad host.
    cafile: ./ca.crt
    # The path to the client certificate file used for TLS
    certfile: ./poseidon.crt
    # The path to the client key file used for TLS
    keyfile: ./poseidon.key
  # Nomad namespace to use. If unset, 'default' is used
  namespace: poseidon

# Configuration of the logger
logger:
  # Log level that is used after reading the config (INFO until then)
  level: DEBUG
