// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package runner

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// InactivityTimerMock is an autogenerated mock type for the InactivityTimer type
type InactivityTimerMock struct {
	mock.Mock
}

// ResetTimeout provides a mock function with given fields:
func (_m *InactivityTimerMock) ResetTimeout() {
	_m.Called()
}

// SetupTimeout provides a mock function with given fields: duration
func (_m *InactivityTimerMock) SetupTimeout(duration time.Duration) {
	_m.Called(duration)
}

// StopTimeout provides a mock function with given fields:
func (_m *InactivityTimerMock) StopTimeout() {
	_m.Called()
}

// TimeoutPassed provides a mock function with given fields:
func (_m *InactivityTimerMock) TimeoutPassed() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
