// Code generated by mockery v2.43.2. DO NOT EDIT.

package runner

import (
	context "context"
	http "net/http"

	dto "github.com/openHPI/poseidon/pkg/dto"

	io "io"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// RunnerMock is an autogenerated mock type for the Runner type
type RunnerMock struct {
	mock.Mock
}

// Destroy provides a mock function with given fields: reason
func (_m *RunnerMock) Destroy(reason DestroyReason) error {
	ret := _m.Called(reason)

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(DestroyReason) error); ok {
		r0 = rf(reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Environment provides a mock function with given fields:
func (_m *RunnerMock) Environment() dto.EnvironmentID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Environment")
	}

	var r0 dto.EnvironmentID
	if rf, ok := ret.Get(0).(func() dto.EnvironmentID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(dto.EnvironmentID)
	}

	return r0
}

// ExecuteInteractively provides a mock function with given fields: ctx, id, stdin, stdout, stderr
func (_m *RunnerMock) ExecuteInteractively(ctx context.Context, id string, stdin io.ReadWriter, stdout io.Writer, stderr io.Writer) (<-chan ExitInfo, context.CancelFunc, error) {
	ret := _m.Called(ctx, id, stdin, stdout, stderr)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteInteractively")
	}

	var r0 <-chan ExitInfo
	var r1 context.CancelFunc
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.ReadWriter, io.Writer, io.Writer) (<-chan ExitInfo, context.CancelFunc, error)); ok {
		return rf(ctx, id, stdin, stdout, stderr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.ReadWriter, io.Writer, io.Writer) <-chan ExitInfo); ok {
		r0 = rf(ctx, id, stdin, stdout, stderr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan ExitInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.ReadWriter, io.Writer, io.Writer) context.CancelFunc); ok {
		r1 = rf(ctx, id, stdin, stdout, stderr)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(context.CancelFunc)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, io.ReadWriter, io.Writer, io.Writer) error); ok {
		r2 = rf(ctx, id, stdin, stdout, stderr)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ExecutionExists provides a mock function with given fields: id
func (_m *RunnerMock) ExecutionExists(id string) bool {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for ExecutionExists")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GetFileContent provides a mock function with given fields: ctx, path, content, privilegedExecution
func (_m *RunnerMock) GetFileContent(ctx context.Context, path string, content http.ResponseWriter, privilegedExecution bool) error {
	ret := _m.Called(ctx, path, content, privilegedExecution)

	if len(ret) == 0 {
		panic("no return value specified for GetFileContent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, http.ResponseWriter, bool) error); ok {
		r0 = rf(ctx, path, content, privilegedExecution)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ID provides a mock function with given fields:
func (_m *RunnerMock) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ListFileSystem provides a mock function with given fields: ctx, path, recursive, result, privilegedExecution
func (_m *RunnerMock) ListFileSystem(ctx context.Context, path string, recursive bool, result io.Writer, privilegedExecution bool) error {
	ret := _m.Called(ctx, path, recursive, result, privilegedExecution)

	if len(ret) == 0 {
		panic("no return value specified for ListFileSystem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool, io.Writer, bool) error); ok {
		r0 = rf(ctx, path, recursive, result, privilegedExecution)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MappedPorts provides a mock function with given fields:
func (_m *RunnerMock) MappedPorts() []*dto.MappedPort {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MappedPorts")
	}

	var r0 []*dto.MappedPort
	if rf, ok := ret.Get(0).(func() []*dto.MappedPort); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.MappedPort)
		}
	}

	return r0
}

// ResetTimeout provides a mock function with given fields:
func (_m *RunnerMock) ResetTimeout() {
	_m.Called()
}

// SetupTimeout provides a mock function with given fields: duration
func (_m *RunnerMock) SetupTimeout(duration time.Duration) {
	_m.Called(duration)
}

// StopTimeout provides a mock function with given fields:
func (_m *RunnerMock) StopTimeout() {
	_m.Called()
}

// StoreExecution provides a mock function with given fields: id, executionRequest
func (_m *RunnerMock) StoreExecution(id string, executionRequest *dto.ExecutionRequest) {
	_m.Called(id, executionRequest)
}

// TimeoutPassed provides a mock function with given fields:
func (_m *RunnerMock) TimeoutPassed() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TimeoutPassed")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// UpdateFileSystem provides a mock function with given fields: ctx, request
func (_m *RunnerMock) UpdateFileSystem(ctx context.Context, request *dto.UpdateFileSystemRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFileSystem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UpdateFileSystemRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRunnerMock creates a new instance of RunnerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRunnerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RunnerMock {
	mock := &RunnerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
