from(bucket: "poseidon")
  |> range(start: -1y)
  |> filter(fn: (r) => r["_measurement"] == "poseidon_environments")
  |> keep(columns: ["id"])
  |> distinct(column: "id")
  |> keep(columns: ["_value"])
