from(bucket: "poseidon/autogen")
  |> range(start: -1y)
  |> filter(fn: (r) => r["_measurement"] == "poseidon_environments")
  |> keep(columns: ["stage"])
  |> distinct(column: "stage")
  |> keep(columns: ["_value"])
