// Code generated by mockery v2.43.2. DO NOT EDIT.

package environment

import (
	context "context"

	dto "github.com/openHPI/poseidon/pkg/dto"
	mock "github.com/stretchr/testify/mock"

	runner "github.com/openHPI/poseidon/internal/runner"
)

// ManagerHandlerMock is an autogenerated mock type for the ManagerHandler type
type ManagerHandlerMock struct {
	mock.Mock
}

// CreateOrUpdate provides a mock function with given fields: ctx, id, request
func (_m *ManagerHandlerMock) CreateOrUpdate(ctx context.Context, id dto.EnvironmentID, request dto.ExecutionEnvironmentRequest) (bool, error) {
	ret := _m.Called(ctx, id, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdate")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.EnvironmentID, dto.ExecutionEnvironmentRequest) (bool, error)); ok {
		return rf(ctx, id, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.EnvironmentID, dto.ExecutionEnvironmentRequest) bool); ok {
		r0 = rf(ctx, id, request)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.EnvironmentID, dto.ExecutionEnvironmentRequest) error); ok {
		r1 = rf(ctx, id, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *ManagerHandlerMock) Delete(id dto.EnvironmentID) (bool, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.EnvironmentID) (bool, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(dto.EnvironmentID) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(dto.EnvironmentID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, id, fetch
func (_m *ManagerHandlerMock) Get(ctx context.Context, id dto.EnvironmentID, fetch bool) (runner.ExecutionEnvironment, error) {
	ret := _m.Called(ctx, id, fetch)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 runner.ExecutionEnvironment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.EnvironmentID, bool) (runner.ExecutionEnvironment, error)); ok {
		return rf(ctx, id, fetch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.EnvironmentID, bool) runner.ExecutionEnvironment); ok {
		r0 = rf(ctx, id, fetch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(runner.ExecutionEnvironment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.EnvironmentID, bool) error); ok {
		r1 = rf(ctx, id, fetch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasNextHandler provides a mock function with given fields:
func (_m *ManagerHandlerMock) HasNextHandler() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasNextHandler")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// List provides a mock function with given fields: ctx, fetch
func (_m *ManagerHandlerMock) List(ctx context.Context, fetch bool) ([]runner.ExecutionEnvironment, error) {
	ret := _m.Called(ctx, fetch)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []runner.ExecutionEnvironment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) ([]runner.ExecutionEnvironment, error)); ok {
		return rf(ctx, fetch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bool) []runner.ExecutionEnvironment); ok {
		r0 = rf(ctx, fetch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]runner.ExecutionEnvironment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = rf(ctx, fetch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NextHandler provides a mock function with given fields:
func (_m *ManagerHandlerMock) NextHandler() ManagerHandler {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NextHandler")
	}

	var r0 ManagerHandler
	if rf, ok := ret.Get(0).(func() ManagerHandler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ManagerHandler)
		}
	}

	return r0
}

// SetNextHandler provides a mock function with given fields: next
func (_m *ManagerHandlerMock) SetNextHandler(next ManagerHandler) {
	_m.Called(next)
}

// Statistics provides a mock function with given fields:
func (_m *ManagerHandlerMock) Statistics() map[dto.EnvironmentID]*dto.StatisticalExecutionEnvironmentData {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Statistics")
	}

	var r0 map[dto.EnvironmentID]*dto.StatisticalExecutionEnvironmentData
	if rf, ok := ret.Get(0).(func() map[dto.EnvironmentID]*dto.StatisticalExecutionEnvironmentData); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[dto.EnvironmentID]*dto.StatisticalExecutionEnvironmentData)
		}
	}

	return r0
}

// NewManagerHandlerMock creates a new instance of ManagerHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManagerHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ManagerHandlerMock {
	mock := &ManagerHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
