// Code generated by mockery v2.9.4. DO NOT EDIT.

package environment

import (
	dto "github.com/openHPI/poseidon/pkg/dto"
	mock "github.com/stretchr/testify/mock"

	runner "github.com/openHPI/poseidon/internal/runner"
)

// ManagerHandlerMock is an autogenerated mock type for the ManagerHandler type
type ManagerHandlerMock struct {
	mock.Mock
}

// CreateOrUpdate provides a mock function with given fields: id, request
func (_m *ManagerHandlerMock) CreateOrUpdate(id dto.EnvironmentID, request dto.ExecutionEnvironmentRequest) (bool, error) {
	ret := _m.Called(id, request)

	var r0 bool
	if rf, ok := ret.Get(0).(func(dto.EnvironmentID, dto.ExecutionEnvironmentRequest) bool); ok {
		r0 = rf(id, request)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(dto.EnvironmentID, dto.ExecutionEnvironmentRequest) error); ok {
		r1 = rf(id, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *ManagerHandlerMock) Delete(id dto.EnvironmentID) (bool, error) {
	ret := _m.Called(id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(dto.EnvironmentID) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(dto.EnvironmentID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id, fetch
func (_m *ManagerHandlerMock) Get(id dto.EnvironmentID, fetch bool) (runner.ExecutionEnvironment, error) {
	ret := _m.Called(id, fetch)

	var r0 runner.ExecutionEnvironment
	if rf, ok := ret.Get(0).(func(dto.EnvironmentID, bool) runner.ExecutionEnvironment); ok {
		r0 = rf(id, fetch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(runner.ExecutionEnvironment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(dto.EnvironmentID, bool) error); ok {
		r1 = rf(id, fetch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: fetch
func (_m *ManagerHandlerMock) List(fetch bool) ([]runner.ExecutionEnvironment, error) {
	ret := _m.Called(fetch)

	var r0 []runner.ExecutionEnvironment
	if rf, ok := ret.Get(0).(func(bool) []runner.ExecutionEnvironment); ok {
		r0 = rf(fetch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]runner.ExecutionEnvironment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(bool) error); ok {
		r1 = rf(fetch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NextHandler provides a mock function with given fields:
func (_m *ManagerHandlerMock) NextHandler() ManagerHandler {
	ret := _m.Called()

	var r0 ManagerHandler
	if rf, ok := ret.Get(0).(func() ManagerHandler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ManagerHandler)
		}
	}

	return r0
}

// SetNextHandler provides a mock function with given fields: m
func (_m *ManagerHandlerMock) SetNextHandler(m ManagerHandler) {
	_m.Called(m)
}

// Statistics provides a mock function with given fields:
func (_m *ManagerHandlerMock) Statistics() map[dto.EnvironmentID]*dto.StatisticalExecutionEnvironmentData {
	ret := _m.Called()

	var r0 map[dto.EnvironmentID]*dto.StatisticalExecutionEnvironmentData
	if rf, ok := ret.Get(0).(func() map[dto.EnvironmentID]*dto.StatisticalExecutionEnvironmentData); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[dto.EnvironmentID]*dto.StatisticalExecutionEnvironmentData)
		}
	}

	return r0
}
