{
 "title": "Poseidon",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "stages",
    "label": "Stage",
    "query": "from(bucket: \"poseidon/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"duration\")\n  |> keep(columns: [\"stage\"])\n  |> distinct(column: \"stage\")\n  |> keep(columns: [\"_value\"])\n"
   },
   {
    "name": "environment_ids",
    "label": "Environment IDs",
    "query": "from(bucket: \"poseidon/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"duration\")\n  |> keep(columns: [\"environment_id\"])\n  |> distinct(column: \"environment_id\")\n  |> keep(columns: [\"_value\"])\n"
   },
   {
    "name": "status_codes",
    "label": "Status Code",
    "query": "from(bucket: \"poseidon/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"duration\")\n  |> keep(columns: [\"status\"])\n  |> distinct(column: \"status\")\n  |> keep(columns: [\"_value\"])\n"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "import \"date\"\n\ndata = from(bucket: \"poseidon/autogen\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1m), stop: date.truncate(t: v.timeRangeStop, unit: 1m))\n  |> filter(fn: (r) => r._field == \"duration\")\n  |> filter(fn: (r) => contains(value: r[\"environment_id\"], set: ${environment_ids:json}))\n  |> filter(fn: (r) => contains(value: r[\"status\"], set: ${status_codes:json}))\n  |> filter(fn: (r) => (not exists r.stage) or contains(value: r[\"stage\"], set: ${stages:json}))\n  |> keep(columns: [\"_time\", \"_value\", \"status\"])\n\nall = data |> set(key: \"status\", value: \"all\")\n\nresult = union(tables: [data, all])\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: true)\n\nif int(v: v.windowPeriod) > int(v: 1m) \n  then result |> aggregateWindow(every: duration(v: int(v: v.windowPeriod) * 20), fn: mean, createEmpty: true)\n  else result |> aggregateWindow(every: duration(v: int(v: v.windowPeriod) * 5), fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"poseidon/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"duration\")\n  |> filter(fn: (r) => contains(value: r[\"environment_id\"], set: ${environment_ids:json}))\n  |> filter(fn: (r) => contains(value: r[\"status\"], set: ${status_codes:json}))\n  |> filter(fn: (r) => (not exists r.stage) or contains(value: r[\"stage\"], set: ${stages:json}))\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n"
    }
   ]
  },
  {
   "title": "Service time (99.9%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"poseidon/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"duration\")\n  |> filter(fn: (r) => contains(value: r[\"environment_id\"], set: ${environment_ids:json}))\n  |> filter(fn: (r) => contains(value: r[\"status\"], set: ${status_codes:json}))\n  |> filter(fn: (r) => (not exists r.stage) or contains(value: r[\"stage\"], set: ${stages:json}))\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])\n  |> aggregateWindow(every: duration(v: int(v: v.windowPeriod) * 10), fn: (tables=<-, column) => tables |> quantile(q: 0.999))\n"
    }
   ]
  },
  {
   "title": "Current environment count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\n\n// The need for the date truncation is caused by Poseidon sending all influx events at the same time when starting up. This way not the last but a random value is displayed.\n// Since in this startup process the highes value is the correct one, we choose the highest value of the last events.\n\ndata = from(bucket: \"poseidon/autogen\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poseidon_environments\")\n  |> group(columns: [\"stage\"], mode:\"by\")\n  |> map(fn: (r) => ({ r with _time: date.truncate(t: r._time, unit: 1m) }))\n\ndeploy_times = data\n  |> last()\n  |> keep(columns: [\"stage\", \"_time\"])\n\njoin(tables: {key1: data, key2: deploy_times}, on: [\"stage\", \"_time\"], method: \"inner\")\n  |> max()\n  |> keep(columns: [\"stage\", \"_value\"])\n  |> rename(columns: {_value: \"\"})\n"
    }
   ]
  },
  {
   "title": "Currently used runners",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"poseidon/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poseidon_used_runners\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> group(columns: [\"stage\"], mode:\"by\")\n  |> last()\n  |> keep(columns: [\"_value\", \"stage\"])\n  |> rename(columns: {_value: \"\"})\n"
    }
   ]
  },
  {
   "title": "Number of Executions",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"poseidon/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poseidon_aws_executions\" or r[\"_measurement\"] == \"poseidon_nomad_executions\")\n  |> filter(fn: (r) => contains(value: r[\"environment_id\"], set: ${environment_ids:json}))\n  |> filter(fn: (r) => (not exists r.stage) or contains(value: r[\"stage\"], set: ${stages:json}))\n  |> filter(fn: (r) => not bool(v: r[\"isDeletion\"]))\n  |> group(columns: [\"environment_id\", \"stage\"], mode:\"by\")\n  |> count()\n  |> keep(columns: [\"_value\", \"environment_id\"])\n  |> rename(columns: {_value: \"env\"})\n"
    }
   ]
  },
  {
   "title": "Execution duration",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"poseidon/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"duration\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poseidon_/execute\" or r[\"_measurement\"] == \"poseidon_/files\" or r[\"_measurement\"] == \"poseidon_/websocket\")\n  |> filter(fn: (r) => contains(value: r[\"environment_id\"], set: ${environment_ids:json}))\n  |> filter(fn: (r) => contains(value: r[\"status\"], set: ${status_codes:json}))\n  |> filter(fn: (r) => (not exists r.stage) or contains(value: r[\"stage\"], set: ${stages:json}))\n  |> filter(fn: (r) => exists r.environment_id)\n  |> drop(columns: [\"_field\", \"environment_type\", \"status\", \"_measurement\"])\n  |> group(columns: [\"environment_id\", \"runner_id\"])\n  |> mean()\n  |> group(columns: [\"environment_id\"])\n  |> mean()\n  |> map(fn: (r) => ({r with _value: r._value * 3.0})) // Each execution has three requests\n  |> rename(columns: {_value: \"env\"})\n"
    }
   ]
  },
  {
   "title": "Executions per runner",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "data = from(bucket: \"poseidon/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => (not exists r.stage) or contains(value: r[\"stage\"], set: ${stages:json}))\n\nrunner_deletions = data\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poseidon_used_runners\")\n  |> filter(fn: (r) => bool(v: r[\"isDeletion\"]))\n  |> keep(columns: [\"id\"])\n  |> rename(columns: {id: \"runner_id\"})\n\nexecutions = data\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poseidon_nomad_executions\" or r[\"_measurement\"] == \"poseidon_aws_executions\")\n  |> filter(fn: (r) => not bool(v: r[\"isDeletion\"]))\n  |> filter(fn: (r) => contains(value: r[\"environment_id\"], set: ${environment_ids:json}))\n  |> keep(columns: [\"_value\", \"environment_id\", \"runner_id\"])\n  |> count()\n\njoin(tables: {key1: executions, key2: runner_deletions}, on: [\"runner_id\"], method: \"inner\")\n  |> keep(columns: [\"_value\", \"environment_id\"])\n  |> mean()\n  |> rename(columns: {_value: \"env\"})\n"
    }
   ]
  },
  {
   "title": "Executions per minute",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"poseidon/autogen\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1m), stop: date.truncate(t: v.timeRangeStop, unit: 1m))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poseidon_aws_executions\" or r[\"_measurement\"] == \"poseidon_nomad_executions\")\n  |> filter(fn: (r) => contains(value: r[\"environment_id\"], set: ${environment_ids:json}))\n  |> filter(fn: (r) => (not exists r.stage) or contains(value: r[\"stage\"], set: ${stages:json}))\n  |> filter(fn: (r) => not bool(v: r[\"isDeletion\"]))\n  |> group(columns: [\"environment_id\", \"stage\"], mode:\"by\")\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: true)\n  |> keep(columns: [\"_value\", \"environment_id\"])\n  |> mean()\n  |> rename(columns: {_value: \"env\"})\n"
    }
   ]
  },
  { "title": "Runner Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Execution duration",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"poseidon/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"duration\")\n  |> filter(fn: (r) => contains(value: r[\"environment_id\"], set: ${environment_ids:json}))\n  |> filter(fn: (r) => contains(value: r[\"status\"], set: ${status_codes:json}))\n  |> filter(fn: (r) => (not exists r.stage) or contains(value: r[\"stage\"], set: ${stages:json}))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poseidon_/execute\" or r[\"_measurement\"] == \"poseidon_/files\" or r[\"_measurement\"] == \"poseidon_/websocket\")\n  |> filter(fn: (r) => exists r.environment_id)\n  |> keep(columns: [\"_time\", \"_value\", \"environment_id\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> map(fn: (r) => ({r with _value: r._value * 3.0})) // Each execution has three requests\n"
    }
   ]
  },
  {
   "title": "Executions per runner",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 36 },
   "targets": [
    {
     "query": "data = from(bucket: \"poseidon/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => (not exists r.stage) or contains(value: r[\"stage\"], set: ${stages:json}))\n\nrunner_deletions = data\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poseidon_used_runners\")\n  |> filter(fn: (r) => bool(v: r[\"isDeletion\"]))\n  |> keep(columns: [\"_time\", \"id\"])\n  |> rename(columns: {id: \"runner_id\"})\n\nexecutions = data\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poseidon_nomad_executions\" or r[\"_measurement\"] == \"poseidon_aws_executions\")\n  |> filter(fn: (r) => not bool(v: r[\"isDeletion\"]))\n  |> filter(fn: (r) => contains(value: r[\"environment_id\"], set: ${environment_ids:json}))\n  |> keep(columns: [\"_value\", \"environment_id\", \"runner_id\"])\n  |> count()\n\njoin(tables: {key1: executions, key2: runner_deletions}, on: [\"runner_id\"], method: \"inner\")\n  |> keep(columns: [\"_value\", \"_time\", \"environment_id\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Executions per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"poseidon/autogen\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1m), stop: date.truncate(t: v.timeRangeStop, unit: 1m))\n  |> filter(fn: (r) => r[\"_field\"] == \"duration\")\n  |> filter(fn: (r) => contains(value: r[\"environment_id\"], set: ${environment_ids:json}))\n  |> filter(fn: (r) => contains(value: r[\"status\"], set: ${status_codes:json}))\n  |> filter(fn: (r) => (not exists r.stage) or contains(value: r[\"stage\"], set: ${stages:json}))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poseidon_/websocket\")\n  |> keep(columns: [\"_time\", \"_value\", \"environment_id\"])\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: true)\n  |> aggregateWindow(every: duration(v: int(v: v.windowPeriod) * 10), fn: mean, createEmpty: true)\n"
    }
   ]
  },
  {
   "title": "Request Body Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "result = from(bucket: \"poseidon/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"request_size\")\n  |> filter(fn: (r) => contains(value: r[\"environment_id\"], set: ${environment_ids:json}))\n  |> filter(fn: (r) => contains(value: r[\"status\"], set: ${status_codes:json}))\n  |> filter(fn: (r) => (not exists r.stage) or contains(value: r[\"stage\"], set: ${stages:json}))\n  |> keep(columns: [\"_time\", \"_value\", \"environment_id\"])\n\nif int(v: v.windowPeriod) > int(v: 1m) \n  then result |> aggregateWindow(every: duration(v: int(v: v.windowPeriod) * 10), fn: mean, createEmpty: true)\n  else result |> aggregateWindow(every: duration(v: int(v: v.windowPeriod) * 5), fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Runner per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"date\"\n\nresult = from(bucket: \"poseidon/autogen\")\n  |> range(start: date.truncate(t: v.timeRangeStart, unit: 1m), stop: date.truncate(t: v.timeRangeStop, unit: 1m))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poseidon_used_runners\")\n  |> filter(fn: (r) => contains(value: r[\"environment_id\"], set: ${environment_ids:json}))\n  |> filter(fn: (r) => (not exists r.stage) or contains(value: r[\"stage\"], set: ${stages:json}))\n  |> filter(fn: (r) => not bool(v: r[\"isDeletion\"]))\n  |> group(columns: [\"environment_id\", \"stage\"], mode:\"by\")\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: true)\n  |> keep(columns: [\"_value\", \"_time\", \"environment_id\"])\n\nif int(v: v.windowPeriod) > int(v: 2m) \n  then result |> aggregateWindow(every: duration(v: int(v: v.windowPeriod) * 30), fn: mean, createEmpty: true)\n  else result |> aggregateWindow(every: duration(v: int(v: v.windowPeriod) * 15), fn: mean, createEmpty: true)\n"
    }
   ]
  },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Prewarming Pool Size",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"poseidon/autogen\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poseidon_poolsize\")\n  |> filter(fn: (r) => contains(value: r[\"environment_id\"], set: ${environment_ids:json}))\n  |> filter(fn: (r) => (not exists r.stage) or contains(value: r[\"stage\"], set: ${stages:json}))\n  |> group(columns: [\"environment_id\", \"stage\"], mode:\"by\")\n  |> last()\n  |> keep(columns: [\"_value\", \"environment_id\"])\n  |> rename(columns: {_value: \"env\"})\n"
    }
   ]
  },
  {
   "title": "Idle Runner",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"poseidon/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poseidon_nomad_idle_runners\" and r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => contains(value: r[\"environment_id\"], set: ${environment_ids:json}))\n  |> filter(fn: (r) => (not exists r.stage) or contains(value: r[\"stage\"], set: ${stages:json}))\n  |> keep(columns: [\"_value\", \"_time\", \"environment_id\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Runner startup duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"poseidon/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poseidon_nomad_idle_runners\")\n  |> filter(fn: (r) => r[\"_field\"] == \"startup_duration\")\n  |> filter(fn: (r) => contains(value: r[\"environment_id\"], set: ${environment_ids:json}))\n  |> filter(fn: (r) => (not exists r.stage) or contains(value: r[\"stage\"], set: ${stages:json}))\n  |> keep(columns: [\"_value\", \"_time\", \"environment_id\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Used Runner",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"poseidon/autogen\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"poseidon_used_runners\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> group(columns: [\"stage\"], mode:\"by\")\n  |> keep(columns: [\"_value\", \"_time\", \"stage\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}