// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package runner

import (
	context "context"
	io "io"

	dto "gitlab.hpi.de/codeocean/codemoon/poseidon/api/dto"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// RunnerMock is an autogenerated mock type for the Runner type
type RunnerMock struct {
	mock.Mock
}

// Add provides a mock function with given fields: id, executionRequest
func (_m *RunnerMock) Add(id ExecutionID, executionRequest *dto.ExecutionRequest) {
	_m.Called(id, executionRequest)
}

// ExecuteInteractively provides a mock function with given fields: request, stdin, stdout, stderr
func (_m *RunnerMock) ExecuteInteractively(request *dto.ExecutionRequest, stdin io.Reader, stdout io.Writer, stderr io.Writer) (<-chan ExitInfo, context.CancelFunc) {
	ret := _m.Called(request, stdin, stdout, stderr)

	var r0 <-chan ExitInfo
	if rf, ok := ret.Get(0).(func(*dto.ExecutionRequest, io.Reader, io.Writer, io.Writer) <-chan ExitInfo); ok {
		r0 = rf(request, stdin, stdout, stderr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan ExitInfo)
		}
	}

	var r1 context.CancelFunc
	if rf, ok := ret.Get(1).(func(*dto.ExecutionRequest, io.Reader, io.Writer, io.Writer) context.CancelFunc); ok {
		r1 = rf(request, stdin, stdout, stderr)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(context.CancelFunc)
		}
	}

	return r0, r1
}

// Id provides a mock function with given fields:
func (_m *RunnerMock) ID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Pop provides a mock function with given fields: id
func (_m *RunnerMock) Pop(id ExecutionID) (*dto.ExecutionRequest, bool) {
	ret := _m.Called(id)

	var r0 *dto.ExecutionRequest
	if rf, ok := ret.Get(0).(func(ExecutionID) *dto.ExecutionRequest); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ExecutionRequest)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(ExecutionID) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// ResetTimeout provides a mock function with given fields:
func (_m *RunnerMock) ResetTimeout() {
	_m.Called()
}

// SetupTimeout provides a mock function with given fields: duration
func (_m *RunnerMock) SetupTimeout(duration time.Duration) {
	_m.Called(duration)
}

// StopTimeout provides a mock function with given fields:
func (_m *RunnerMock) StopTimeout() {
	_m.Called()
}

// TimeoutPassed provides a mock function with given fields:
func (_m *RunnerMock) TimeoutPassed() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// UpdateFileSystem provides a mock function with given fields: request
func (_m *RunnerMock) UpdateFileSystem(request *dto.UpdateFileSystemRequest) error {
	ret := _m.Called(request)

	var r0 error
	if rf, ok := ret.Get(0).(func(*dto.UpdateFileSystemRequest) error); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
