name: Python CI

on:
  push:
    paths: [ deploy/grafana-dashboard/** ]
  pull_request:
    paths: [ deploy/grafana-dashboard/** ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: pipenv
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - run: pipenv install
        working-directory: deploy/grafana-dashboard
      - name: Use Sample Environments
        run: cp environments.json.sample environments.json
        working-directory: deploy/grafana-dashboard
      - name: Create Grafana Dashboard JSON
        run: pipenv run python main.py
        working-directory: deploy/grafana-dashboard
      - name: Upload Grafana Dashboard JSON
        uses: actions/upload-artifact@v4
        with:
          name: grafana-dashboard.json
          path: deploy/grafana-dashboard/main.json
